### ISSUE TITLE
Unit 7

### ISSUE THREAD

**Issue by NickyWinder** [LanceGardner/The-Wolf-Garden#6]
My final version of 7

[UNIT 7 NW.docx](https://github.com/LanceGardner/The-Wolf-Garden/files/1185667/UNIT.7.NW.docx)

**Comment by LanceGardner** [comment]
[UNIT 7 Chapters 2-4 edited-06.08.17.docx](https://github.com/LanceGardner/The-Wolf-Garden/files/1203375/UNIT.7.Chapters.2-4.edited-06.08.17.docx)
